### ISSUE TITLE
about training code

### ISSUE THREAD

**Issue by tikboaHIT** [histocartography/patho-quant-explainer#2]
Thank your excellent work!!! 

have you plan to release the training process code?

**Comment by guillaumejaume** [comment]
Hi, 

We didn't plan to add the training script on this repository but feel free to adapt this script:

https://github.com/histocartography/hact-net/blob/main/core/train.py that can be run with:

```
python train.py --cg_path <SOME-SAVE-PATH>/hact-net-data/cell_graphs/ --config_fpath ../data/config/cg_bracs_cggnn_7_classes_pna.yml -b 8 --in_ram --epochs 60 -l 0.0005 
```

used in our other paper "Hierarchical Graph Representations in Digital Pathology". Of course, it depends the type of GNN layer you wanna use (GIN, PNA), the number of classes (3, 7). Let me know if you encounter issues while training the cell graph GNN.

**Comment by tikboaHIT** [comment]
Thank you! I will try.
