### ISSUE TITLE
Questions on the Separability Scores

### ISSUE THREAD

**Issue by Samyu0304** [histocartography/patho-quant-explainer#4]
Hi, Thanks a lot for open-sourcing the code and the histocartography package. The thing is I try to evaluate different explainers with the downloaded cell graphs and important scores (.zipfile) in Step 3. And I find the separability scores are different from those reported in your paper.  I wonder if there is something wrong with my implementation. And I think there is nothing to do with the pretrained GNN, since it doesn't appear in run_qualitative_results.py.  I confirm the usage of the previous version of the BRACS dataset and the pretained model reaches a Weighted F1 score: 0.7380407862790188 and Acc: 0.7460063897763578.

**Comment by guillaumejaume** [comment]
Hi, after double checking, it seems that you obtain the expected numbers. The difference in range compared to the paper comes from a different node importance normalization. In this case, the absolute values convey little information (we talk about Wasserstein distances), but the numbers should be analyzed relatively.

**Comment by Samyu0304** [comment]
Thank you for your time. I notice that you use minmax_scale to normalize the node important score, as shown in AttributeSeparability.normalize_node_importance in run_qualitative_analysis.py. I change the minmax_scale into maxabs_scale but the results don't change. Therefore I guess the problem is not on the normalization scheme. Could it be other factors that I ignore? Also could you please provide more details on your node importance normalization to help me reproduce the results?

**Comment by guillaumejaume** [comment]
The difference concerns the way histograms are constructed and normalized (both x and y axis). Scaling differences also depend on the way you set the x axis in the AUC computation (between 0 and 1, vs unnormalized between 5 and 50 in our experiments). As soon as I have time, I'll look into that.

**Comment by Samyu0304** [comment]
Hi, I find that scaling the x-axis in the AUC computation to [0,7]~[0,8] in the AttributeSeparability.process() of run_qualitative_analysis.py will lead to a similar result of your paper.
