### ISSUE TITLE
The data downloading is not available

### ISSUE THREAD

**Issue by WenchaoHanSRI** [histocartography/patho-quant-explainer#5]
Hi, 
I am trying to implement the code here. I used the link to access the data. I have registered based on the instruction. Every time, I click on to the link of "Regions of interest set", the link brings me to a blank page. Could you help me with this? I am not sure if I did something wrong.

**Comment by guillaumejaume** [comment]
Hi, 

Are you able to access the FTP server where the data are stored, or just the "Regions of interest set" is not accessible? I tried to connect, and it seems to work as expected on my side. 

G.

**Comment by WenchaoHanSRI** [comment]
Thank you for your quick response! Yes, I would be able to access the server. All of the links brings me to a new blank page. It seems that the problem is at my end if you can access. I will try to use a different computer to try again! Will keep you posted.

**Comment by WenchaoHanSRI** [comment]
Hi, I have tried to use a different computer. It looks the same to me. Sorry that I misunderstood your question earlier. I cannot access the FTP server. When I click on to any of the dataset link, it asked me "if I want to use the associated app to open the link". I chose an web browser. Then, each time, the link brings me to a blank page. Should I use a specific app to open the link?

**Comment by WenchaoHanSRI** [comment]
Bear my ignorance, I copied URL to file explorer, and it works.
